Repository road86/bahis-desk, pull requests merged in 2023-03, with the labels that each got.

#68 fix:pointed to latest odkformrenderer commit
  package.json
  yarn.lock
Labels: bug, enhancement

#69 feat: add GitHub Actions
  .github/workflows/add-to-project.yml
  .github/workflows/check-pr-title-and-add-labels.yml
  .github/workflows/synchronise-labels.yml
Labels: enhancement

#71 fix: prevent local duplication error caused by syncing
  package.json
  public/electron.js
  public/modules/syncFunctions.js
  src/App/App.tsx
  src/components/page/Header/index.tsx
Labels: bug

#74 feat: remove mouzas
  src/components/Form/index.tsx
Labels: feature
